🚀 启动 TuDo 服务器...
📍 地址: http://127.0.0.1:8000
🔧 调试模式: True
🔥 自动重载: True
[2025-05-27 16:46:18 +0800] [46815] [DEBUG] 

                 Sanic
         Build Fast. Run Fast.


[2025-05-27 16:46:18 +0800] [46815] [INFO] Sanic v23.12.1
[2025-05-27 16:46:18 +0800] [46815] [INFO] Goin' Fast @ http://127.0.0.1:8000
[2025-05-27 16:46:18 +0800] [46815] [INFO] app: TuDoServer
[2025-05-27 16:46:18 +0800] [46815] [INFO] mode: debug, single worker
[2025-05-27 16:46:18 +0800] [46815] [INFO] server: sanic, HTTP/1.1
[2025-05-27 16:46:18 +0800] [46815] [INFO] python: 3.9.6
[2025-05-27 16:46:18 +0800] [46815] [INFO] platform: macOS-14.1.1-arm64-arm-64bit
[2025-05-27 16:46:18 +0800] [46815] [INFO] auto-reload: enabled, /Users/ikvs2212304p/Code/opensource/tuDo/server/app
[2025-05-27 16:46:18 +0800] [46815] [INFO] packages: sanic-routing==23.12.0
[2025-05-27 16:46:18 +0800] [46815] [DEBUG] Creating multiprocessing context using 'spawn'
[2025-05-27 16:46:18 +0800] [46815] [DEBUG] [34mStarting a process: [1m[38;2;255;13;104mSanic-Server-0-0[0m
[2025-05-27 16:46:18 +0800] [46815] [DEBUG] [34mStarting a process: [1m[38;2;255;13;104mSanic-Reloader-0[0m
🔗 连接数据库: sqlite://db.sqlite3
✅ 数据库表创建成功
[2025-05-27 16:46:18 +0800] [46826] [DEBUG] [34mProcess ack: [1m[38;2;255;13;104mSanic-Server-0-0 [34m[46826][0m
[2025-05-27 16:46:18 +0800] [46826] [INFO] Starting worker [46826]
Process Sanic-Reloader-0:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ikvs2212304p/Code/opensource/tuDo/server/venv/lib/python3.9/site-packages/sanic/worker/reloader.py", line 65, in __call__
    self.reload(",".join(changed) if changed else "unknown")
  File "/Users/ikvs2212304p/Code/opensource/tuDo/server/venv/lib/python3.9/site-packages/sanic/worker/reloader.py", line 78, in reload
    self._publisher.send(message)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
